### PR TITLE
Add short alias for color names.

### PR DESCRIPTION
**Pull request by devxoul**
@rinatkhanov suggested in #4. (Thanks!)

`UIColor.blackColor` -> `UIColor.black`
`UIColor.darkGrayColor` -> `UIColor.darkGray`
`UIColor.lightGrayColor` -> `UIColor.lightGray`
`UIColor.whiteColor` -> `UIColor.white`
`UIColor.grayColor` -> `UIColor.gray`
`UIColor.redColor` -> `UIColor.red`
`UIColor.greenColor` -> `UIColor.green`
`UIColor.blueColor` -> `UIColor.blue`
`UIColor.cyanColor` -> `UIColor.cyan`
`UIColor.yellowColor` -> `UIColor.yellow`
`UIColor.magentaColor` -> `UIColor.magenta`
`UIColor.orangeColor` -> `UIColor.orange`
`UIColor.purpleColor` -> `UIColor.purple`
`UIColor.brownColor` -> `UIColor.brown`
`UIColor.clearColor` -> `UIColor.clear`

Or even(?) shorter: `UIColor.red` -> `Color.red`

### CODE REVIEW

**Comment by rinatkhanov** [comment]
Awesome, I like `Color` more than having separate `UIColor` / `NSColor`.

**Comment by rinatkhanov** [comment]
(Also, don't forget to update README)

**Comment by devxoul** [comment]
Oh yeah, README.

**Comment by devxoul** [comment]
Updated README.md and uploaded 0.1.3 to CocoaPods!

**Pull request merged**
